version: '3.8'

services:
  servico-a:
    build:
      context: ./servico-a
    ports:
      - "8080:8080"
    depends_on:
      - servico-b

  servico-b:
    build:
      context: ./servico-b
    ports:
      - "8081:8081"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/collector-otel-config.yaml" ]
    volumes:
      - ./collector-otel-config.yaml:/etc/collector-otel-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"