
FROM golang:latest

WORKDIR /app

CMD ["tail", "-f", "/dev/null"]
#COPY . .
#RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudrun
#ENTRYPOINT [ "/app/cloudrun" ] 


#FROM scratch 
#COPY --from=build /app/cloudrun .
#ENTRYPOINT [ "./cloudrun" ]